name = "evite-os"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"

[[d1_databases]]
binding = "DB"
database_name = "evite-os"
database_id = "8ed081e2-2a09-4152-aaac-f2046d599e92"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "evite-os-images"

[[send_email]]
name = "SEND_EMAIL"

[vars]
FROM_PHONE = "+1234567890"
FROM_EMAIL = "noreply@yourdomain.com"
APP_URL = "https://yourdomain.com"

# Secrets — set with: wrangler secret put TELNYX_API_KEY
